name: Publish Package and Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      # can't test package because ffmpeg is not installed
      # - name: Test package
      #   run: uv run pytest

      - name: Lint package
        run: uvx ruff check

      - name: Build package
        run: uv build

      - name: Publish package
        run: uv publish --token ${{ secrets.PYPI_TOKEN }}

  build-and-push-docker:
    runs-on: ubuntu-latest
    needs: publish-package

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./docker/
          push: true
          tags: shoopmywoop/tonie-sync:latest
